version: "3"

services:

  redis-hastebin:
    image: redis:alpine
    container_name: redis-hastebin
    command: >
      sh -c "redis-server --bind redis-hastebin --port 6379"

  hastebin:
    image: gfnord/hastebin:latest
    build:
      context: ./hastebin
      dockerfile: Dockerfile
    ports:
      - "80:7777"
    depends_on:
      - redis-hastebin
    command: sh -c "dockerize -wait tcp://redis-hastebin:6379 -timeout 300s -wait-retry-interval 30s npm start"
